docker-orchestration/osrm-backend/Dockerfile, docker-orchestration/osrm-backend/docker-entrypoint.sh
Add docker entry point and adjust docker file for osrm-backend.
=> Add docker entry point and adjust docker file

include/extractor/packed_osm_ids.hpp, third_party/libosmium/include/osmium/io/detail/pbf_decoder.hpp, third_party/libosmium/include/osmium/osm/types.hpp
=> Feat: Implement logic for processing professional vender's pbf with OSRM

docker-orchestration/README.md, docker-orchestration/osrm-backend/Dockerfile, docker-orchestration/osrm-backend/README.md, docker-orchestration/osrm-backend/docker-entrypoint.sh, docker-orchestration/osrm-backend/example-berlin-osm.md, docs/design/osrm-with-telenav-traffic.md
https://github.com/Telenav/osrm-backend/issues/20
https://github.com/Telenav/osrm-backend/issues/1
https://github.com/Telenav/osrm-backend/issues/2
https://github.com/Telenav/osrm-backend/issues/3
=> Improve compile data in docker and publish data

docker-orchestration/osrm-backend/Dockerfile, docker-orchestration/osrm-backend/docker-entrypoint.sh, docker-orchestration/osrm-backend/example-berlin-osm.md
https://github.com/Telenav/osrm-backend/issues/23
https://github.com/Telenav/osrm-backend/issues/23
=> Use PBF_FILE_NAME + IMAGE_TAG as DATA_VERSION to shown in every response

docker-orchestration/osrm-backend/docker-entrypoint.sh
https://github.com/Telenav/osrm-backend/issues/26
https://github.com/Telenav/osrm-backend/issues/26
=> Add routed_no_traffic_startup

traffic_updater/go/gen-go/proxy/proxy.go, traffic_updater/go/gen-go/proxy/proxy_service-remote/proxy_service-remote.go, traffic_updater/proxy.thrift
https://github.com/Telenav/osrm-backend/issues/22
=> Update proxy thrift RPC protocol 

docker-orchestration/osrm-backend-dev/Dockerfile, docker-orchestration/osrm-backend/Dockerfile, docker-orchestration/osrm-backend/docker-entrypoint.sh, traffic_updater/.gitignore, traffic_updater/go/go.mod, traffic_updater/go/go.sum
https://github.com/Telenav/osrm-backend/issues/35
https://github.com/Telenav/osrm-backend/issues/31
=> Use Go Modules to manage Go code's dependency

traffic_updater/go/osrm_traffic_updater/dumper_statistic.go, traffic_updater/go/osrm_traffic_updater/dumper_statistic_test.go, traffic_updater/go/osrm_traffic_updater/osrm_traffic_updater.go, traffic_updater/go/osrm_traffic_updater/speed_table_dumper.go
https://github.com/Telenav/osrm-backend/issues/43
=> Add traffic records matched statistics and total processing time

docker-orchestration/osrm-backend-dev/Dockerfile
https://github.com/Telenav/osrm-backend/issues/69
https://github.com/Telenav/osrm-backend/issues/69
=> chore: upgrade golang to 1.13

docker-orchestration/osrm-backend/docker-entrypoint.sh, integration/cmd/osrm-traffic-updater/osrm_traffic_updater.go, integration/pkg/trafficproxyclient/get.go
https://github.com/Telenav/osrm-backend/issues/75
https://github.com/Telenav/osrm-backend/issues/71
=> Integrate Incident 

docker-orchestration/osrm-backend/Dockerfile, docker-orchestration/osrm-backend/README.md
- use `telenavmap` dockerhub namespace.
=> telenavmap docker repo

docker-orchestration/README.md, docker-orchestration/osrm-backend-dev/README.md, docker-orchestration/osrm-backend-within-mapdata/Dockerfile, docker-orchestration/osrm-backend/README.md, docker-orchestration/osrm-backend/docker-entrypoint.sh
https://github.com/Telenav/osrm-backend/issues/95
=> Package docker image within mapdata by smaller layers

src/util/log.cpp
https://github.com/Telenav/osrm-backend/issues/105
=> chore: debug log only controls by  in runtime, not compile time

src/extractor/extractor_callbacks.cpp
https://github.com/Telenav/osrm-backend/issues/104
=> fix: wayid overflow, refer to https://github.com/Project-OSRM/osrm-backend/pull/5381

integration/cmd/search-adhoc-request/flags.go, integration/cmd/search-adhoc-request/main.go, integration/pkg/api/search/coordinate/coordinate.go, integration/pkg/api/search/nearbychargestation/request.go, integration/pkg/api/search/nearbychargestation/response.go, integration/pkg/api/search/options/key.go, integration/pkg/api/search/options/value.go
Only support nearest charge station search for now.
#132
#132
=> Implement initial connector with Telenav search

integration/cmd/oasis/main.go, integration/oasis/handler.go, integration/pkg/api/oasis/request.go
Generate single way charge station based on given origin and destination.
https://github.com/Telenav/osrm-backend/issues/133
https://github.com/Telenav/osrm-backend/issues/128
https://github.com/Telenav/osrm-backend/issues/128#issuecomment-571350305
=> feat: fake deployment for oasis service

integration/cmd/oasis/main.go, integration/oasis/handler.go, integration/oasis/has_enough_energy.go, integration/oasis/has_enough_energy_test.go, integration/oasis/osrmconnector/osrmhttpclient.go
=> feat: implement logic to handle no charge station needed.

integration/oasis/charge_station_searcher.go, integration/oasis/searchconnector/connector.go, integration/oasis/searchconnector/doc.go, integration/oasis/searchconnector/searchhttpclient.go, integration/oasis/searchconnector/searchrequest.go, integration/pkg/api/search/nearbychargestation/request.go, integration/pkg/api/search/options/key.go
=> feat: implement search connector

integration/oasis/osrmconnector/connector.go, integration/oasis/osrmconnector/osrmhttpclient.go, integration/oasis/osrmconnector/osrmhttpclient_test.go
=> feat: implement osrm table request and response in osrmconnector

integration/oasis/osrmconnector/route_requester.go, integration/oasis/osrmconnector/table_requester.go, integration/oasis/reachable_by_single_charge_test.go, integration/oasis/stationfinder/basic_finder_test.go, integration/oasis/stationfinder/orig_station_finder_test.go, integration/oasis/stationfinder/stations_iterator_alg.go, integration/oasis/stationfinder/stations_iterator_alg_test.go, integration/pkg/api/osrm/table/mock_response.go
=> feat: implement algorithm to calculate cost between two stations

.github/workflows/autobuild-osrm-backend-dev.yml, .github/workflows/autobuild-osrm-backend.yml, .github/workflows/release-osrm-backend-dev.yml, .github/workflows/release-osrm-backend.yml, README.md, docker-orchestration/README.md, docker-orchestration/osrm-backend-dev/Dockerfile, docker-orchestration/osrm-backend/Dockerfile, docker-orchestration/osrm-backend/README.md
https://github.com/Telenav/osrm-backend/issues/191
https://github.com/Telenav/osrm-backend/issues/192
https://github.com/Telenav/osrm-backend/wiki/Automation-by-GitHub-Actions
=> Build/Release osrm-backend-dev and osrm-backend docker automation by GitHub Actions

integration/cmd/osrm-files-extractor/main.go, integration/osrmfiles/dotcnbg/contents.go, integration/osrmfiles/dotnbgnodes/contents.go, integration/osrmfiles/dotosrm/contents.go, integration/osrmfiles/osrmtype/compressed_node_based_graph_edge.go, integration/osrmfiles/osrmtype/compressed_node_based_graph_edge_test.go
Closes #126 
Doc: https://github.com/Telenav/open-source-spec/blob/master/osrm/doc/osrm-toolchain-files/map.osrm.cnbg.md
=> Understanding .osrm.cnbg

integration/oasis/stationfinder/stations_iterator_alg.go, integration/oasis/stationfinder/stations_iterator_alg_test.go
issue: https://github.com/Telenav/osrm-backend/issues/143
=> fix: Record location inforamtion on neighbors

integration/oasis/stationgraph/graph.go, integration/oasis/stationgraph/graph_test.go, integration/oasis/stationgraph/node.go, integration/oasis/stationgraph/query_heap.go
issue: https://github.com/Telenav/osrm-backend/issues/143
=> fix: fix issue in graph for handling charge state

docker-orchestration/osrm-backend/Dockerfile
Closes https://github.com/Telenav/osrm-backend/issues/212
We may start to release from this/next sprint.
=> Use osrm-backend-dev/v1 as base image for stable purpose

profiles/car-unidb.lua, profiles/lib-unidb/access.lua, profiles/lib-unidb/destination.lua, profiles/lib-unidb/guidance.lua, profiles/lib-unidb/maxspeed.lua, profiles/lib-unidb/measure.lua, profiles/lib-unidb/pprint.lua, profiles/lib-unidb/profile_debugger.lua, profiles/lib-unidb/relations.lua, profiles/lib-unidb/sequence.lua, profiles/lib-unidb/set.lua, profiles/lib-unidb/tags.lua, profiles/lib-unidb/utils.lua, profiles/lib-unidb/way_handlers.lua
Lua profile supports unidb.
Duplicate car.lua and rename car-unidb.lua.
Duplicate the folder of lib and rename lib-unidb.
Since almost half of files in lib folder need to be changed, instead of duplicate each of them in original folder, duplicate the whole folder.
=> add new car profile and libs for unidb

.github/PULL_REQUEST_TEMPLATE.md
issue: https://github.com/Telenav/osrm-backend/issues/216
Update pull request template and add links of contribution guidelines https://github.com/Telenav/osrm-backend/wiki/Contribution-Guidelines
=> fix: update pull request template and link with contribution guidelines.

integration/doc/oasis/api.md
https://github.com/Telenav/osrm-backend/issues/128
=> feat: Add api document

.github/workflows/release-go-cmd-oasis.yml
issue: https://github.com/Telenav/osrm-backend/issues/226
=> feat: add release action for oasis service

integration/oasis/handler.go, integration/oasis/has_enough_energy.go, integration/oasis/osrmhelper/helper.go, integration/oasis/reachable_by_multiple_charge.go, integration/oasis/solution/solution.go, integration/pkg/api/oasis/mock_response.go
issue: https://github.com/Telenav/osrm-backend/issues/143
- Enable logic for `generateSolutions4MultipleCharge`
- Implement logic for converting from IngernalSolution to External response
- Move function of `GenerateFakeResponse` from `handler` to `oasis/mock_response`
- Move function of `generateOASISResponse4NoChargeNeeded` from `handler` to `has_enough_energy`
- Move function of `RequestRoute4InputOrigDest` from `handler` to `osrmhelper`
=> feat: integrate logic for handling multiple charge stations

integration/traffic/historicalspeed/daily_patterns.go, integration/traffic/historicalspeed/daily_patterns_test.go, integration/traffic/historicalspeed/historical_speeds.go, integration/traffic/historicalspeed/ways_mapping.go, integration/traffic/interface.go
Closes #255 
- Implemented `QueryHistoricalSpeed` Interface; 
- TODO: convert UTC time to Local Time (#220)
=> Query Historical Speed on a specified time for way

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG-FORK.md
Closes https://github.com/Telenav/osrm-backend/issues/234, https://github.com/Telenav/osrm-backend/issues/193
- improved pull request template
- added CHANGELOG-FORK.md
- Want to contribute? Great! First, please read this page [Contribution Guidelines](https://github.com/Telenav/osrm-backend/wiki/Contribution-Guide …
=> Add CHANGELOG-FORK.md and improve pull request template 

CHANGELOG-FORK.md
Closes https://github.com/Telenav/osrm-backend/issues/294
=> Promote Unreleased to v10.2.0

.github/workflows/release-go-cmd-oasis.yml, .github/workflows/release-go-cmd-osrm-files-extractor.yml, .github/workflows/release-go-cmd-traffixproxy-cli.yml, CHANGELOG-FORK.md, docker-orchestration/osrm-backend/Dockerfile, integration/.gitignore, integration/cmd/oasis/flags.go, integration/cmd/oasis/main.go, integration/cmd/oasis/version.go, integration/cmd/osrm-files-extractor/flags.go, integration/cmd/osrm-files-extractor/main.go, integration/cmd/osrm-files-extractor/version.go, integration/cmd/osrm-rankd/flags.go, integration/cmd/osrm-rankd/main.go, integration/cmd/osrm-rankd/monitor.go, integration/cmd/osrm-rankd/version.go, integration/cmd/trafficproxy-cli/flags.go, integration/cmd/trafficproxy-cli/main.go, integration/cmd/trafficproxy-cli/version.go
Closes https://github.com/Telenav/osrm-backend/issues/318
- Add version info(appVersion, buildTime and gitCommit) when build golang binaries inside docker 
- Add version info on the golang binaries that will release to assets
- Currently only apply the versioning on golang binaries `trafficproxy-cli`, …
=> Golang binary versioning

CHANGELOG-FORK.md
Closes https://github.com/Telenav/osrm-backend/issues/336
- Promote Unreleased to v10.3.0 for new release 
- If your PR is still work in progress please …
=> Promote Unreleased to v10.3.0

CHANGELOG-FORK.md, integration/doc/oasis/README.md, integration/doc/oasis/architecture_design.md, integration/doc/oasis/charge_station_based_routing.md, integration/doc/oasis/container_design.md, integration/doc/oasis/search_chargestations_along_route.md
issue: https://github.com/Telenav/osrm-backend/issues/366
Closes #366 
A summary description for what the PR achieves.     
Add document for charge station based routing      
- If your PR is still work in progress …
=> doc: add document for charge station based routing

CHANGELOG-FORK.md, docker-orchestration/osrm-backend-dev/Dockerfile, docker-orchestration/osrm-backend/Dockerfile
Closes https://github.com/Telenav/osrm-backend/issues/374
=> Upgrade osrm-backend-dev env

CHANGELOG-FORK.md, docker-orchestration/osrm-backend-dev/Dockerfile
Closes https://github.com/Telenav/osrm-backend/issues/379
Tested details see https://github.com/Telenav/osrm-backend/issues/379#issuecomment-714391711
- If …
=> Support run cucumber test and code format in osrm-backend-dev

CHANGELOG-FORK.md, docker-orchestration/osrm-backend/Dockerfile
Closes https://github.com/Telenav/osrm-backend/issues/381
=> Upgrade base image to osrm-backend-dev:v2

CHANGELOG-FORK.md, integration/cmd/wayid2nodeid-extractor/wayid2nodeids_extractor.go, integration/util/osmpatch/patch.go, integration/util/osmpatch/patch_test.go
Closes https://github.com/Telenav/osrm-backend/issues/387
=> Filter invalid OSM ways

CHANGELOG-FORK.md, docker-orchestration/osrm-backend-dev/Dockerfile
Closes https://github.com/Telenav/osrm-backend/issues/398
=> Upgrade dev docker env to debian:buster
