traffic_updater/go/osrm_traffic_updater/get_telenav_traffic.go, traffic_updater/go/osrm_traffic_updater/osrm_traffic_updater_test.go, traffic_updater/go/osrm_traffic_updater/speed_table_dumper_test.go, traffic_updater/go/osrm_traffic_updater/way2nodeids_loader.go, traffic_updater/go/osrm_traffic_updater/way2nodeids_loader_test.go, traffic_updater/go/snappy_command/snappy_command.go, traffic_updater/go/wayid2nodeid_extractor/wayid2nodeids_extractor.go
chore: format our golang codes by 'goreturns -l -w .'
Be noted that we don't need to format generated codes, e.g. generated by thrift
https://github.com/Telenav/osrm-backend/issues/45
=> chore: format our golang codes by 'goreturns -l -w .'

docker-orchestration/osrm-backend/Dockerfile
use osrm-backend-dev as runstage, will have a little bigger size but easy for debug.
NOTE that we could make the runstage smaller as before if we have a big team to maintain different things.
https://github.com/Telenav/osrm-backend/issues/52
=> use osrm-backend-dev as runstage for easy debugging

integration/oasis/chargingstrategy/charge_strategy_creator.go, integration/oasis/chargingstrategy/chargingstrategy.go, integration/oasis/chargingstrategy/chargingstrategy_test.go, integration/oasis/chargingstrategy/null_charge_strategy.go, integration/oasis/stationgraph/station_graph.go, integration/oasis/stationgraph/station_graph_test.go, integration/util/float_operation.go, integration/util/float_operation_test.go
issue: https://github.com/Telenav/osrm-backend/issues/143
- Calculate charging cost for given status and target status.  
+ `ChargeStrategy` creates several charge solutions via function `CreateChargingStrategies`, which means charge battery to a certain certain energy level.
+ When user reaches a charge station, he has a inital arrival energy and target status, he could use `EvaluateCost` to calculate cost needed, such as time, money, etc.
- Add NullChargeStrategy for unit tests
- Fix the issue of hard coded `chargeTime`
- Remove test cases for chargeEnergy, which will be added later in the future pull
=> feat: Implement function to calcualte charge cost

integration/oasis/handler.go, integration/oasis/reachable_by_multiple_charge.go, integration/oasis/reachable_by_single_charge.go, integration/oasis/stationgraph/graph.go, integration/oasis/stationgraph/graph_test.go, integration/oasis/stationgraph/node.go, integration/oasis/stationgraph/station_graph.go, integration/oasis/stationgraph/station_graph_test.go
- This pull need https://github.com/Telenav/osrm-backend/pull/204 to be merged first.
- After `stationGraph` is construct, it could call algorithm in `graph` to calculate best solution and generate result in `solution` format
- Record location information on `node`
- Fix bug in `stationGraph` during constructing `graph`, which has expectation in node sequence
- Make unit test work with Dijkstra especially for arrival energy/charging time part.  (More unit test will be added later.)
=> Feature/Implement function of GenerateChargeSolutions for station_graph

src/extractor/graph_compressor.cpp
Closes https://github.com/Telenav/osrm-backend/issues/198
This PR is cherry-pick from https://github.com/Project-OSRM/osrm-backend/pull/5384 which don't know when can be merged.
=> correct comments for "compress edge if it crosses a traffic signal" 

.github/workflows/release-go-cmd-oasis.yml, .github/workflows/release-go-cmd-osrm-files-extractor.yml, .github/workflows/release-go-cmd-traffixproxy-cli.yml, .github/workflows/release-osrm-backend.yml
Closes https://github.com/Telenav/osrm-backend/issues/251 https://github.com/Telenav/osrm-backend/issues/252
- Remove `linux-386` when release go binaries; 
- Follow our proposal to release osrm-backend(follow semver, start from `v10.0.1`).
=> Improve Release Actions

integration/cmd/oasis/flags.go, integration/service/oasis/stationfinder/cloudfinder/cloud_station_finder.go, integration/service/oasis/stationfinder/cloudfinder/dest_station_finder.go, integration/service/oasis/stationfinder/cloudfinder/dest_station_finder_mock.go, integration/service/oasis/stationfinder/cloudfinder/dest_station_finder_test.go, integration/service/oasis/stationfinder/cloudfinder/low_energy_location_station_finder.go, integration/service/oasis/stationfinder/cloudfinder/low_energy_location_station_finder_mock.go, integration/service/oasis/stationfinder/cloudfinder/low_energy_location_station_finder_test.go, integration/service/oasis/stationfinder/cloudfinder/orig_station_finder.go, integration/service/oasis/stationfinder/cloudfinder/orig_station_finder_mock.go, integration/service/oasis/stationfinder/cloudfinder/orig_station_finder_test.go, integration/service/oasis/stationfinder/localfinder/dest_station_local_finder.go, integration/service/oasis/stationfinder/localfinder/low_energy_location_local_finder.go, integration/service/oasis/stationfinder/localfinder/orig_station_local_finder.go, integration/service/oasis/stationfinder/station_finder_factory.go, integration/service/oasis/stationfinder/stationfinderalg/stations_iterator_alg_test.go
issue: https://github.com/Telenav/osrm-backend/issues/279
- Use `struct embedding` to avoid function calling to interface implemented in base class
+ https://golang.org/doc/effective_go.html#embedding 
+ https://github.com/wangyoucao577/golang/tree/master/effective-go#embedding
+ https://play.golang.org/p/F6gmScefu5s
+ https://play.golang.org/p/xekNSmRLk9H
- Remove unnecessary `go-routine` in test
- Adjust name
=> refactor: use `struct embedding` to avoid interface forwarding

CHANGELOG-FORK.md, docs/http.md, include/engine/api/route_api.hpp
Closes https://github.com/Telenav/osrm-backend/issues/276
- Use `string` instead of `Number` to store nodeid in JSON to avoid overflow since the `Number` is implemented by `double` that may insufficient for long `uint64_t`.        
NOTE that it's a short-term solution to unblock our post process at this moment. …
=> Fix invalid nodes in annotations of response

CHANGELOG-FORK.md, docker-orchestration/osrm-backend-within-mapdata/Dockerfile, docker-orchestration/osrm-backend/docker-entrypoint.sh
Closes https://github.com/Telenav/osrm-backend/issues/284
- Build nodes2way DB after osrm mapdata compiled 
- Package `nodes2way.db.snappy` into `osrm-backend-within-mapdata` docker
- Want to contribute? Great! First, please read this page [Contribution Guidelines](https://github.com/Telenav/osrm-backend/wiki/Contr …
=> Build nodes2way DB when compile mapdata

CHANGELOG-FORK.md, integration/cmd/osrm-ranking/flags.go, integration/cmd/osrm-ranking/main.go, integration/cmd/osrm-ranking/monitor.go, integration/pkg/api/osrm/route/response.go, integration/service/ranking/handler.go, integration/service/ranking/retrieve_ways.go, integration/service/ranking/route_by_osrm.go
Closes https://github.com/Telenav/osrm-backend/issues/257
- `Annotation/Nodes` compatible with both int64 array and string array incoming;   
- Add `Ways` in `Annotation` of OSRM API; 
- Load and monitor `nodes2way.db` in `osrm-ranking`;    
- Retrieve `annotation/ways` from `annotation/nodes` when recieved OSRM …
=> Expose Annotation/ways

.gitattributes, CHANGELOG-FORK.md
Resolves https://github.com/Telenav/osrm-backend/issues/304
- Add `merge=union` for resolving merge confilcits automatically on `CHANGELOG-FORK.md`
Be aware that it's not supported by GitHub but only locally(works on GitLab, not sure on Bitbucket). But anyway, it can help at least on local. And let's keep an eye …
=> Add `merge=union` for resolving merge confilcits automatically on CHANGELOG-FORK.md

CHANGELOG-FORK.md, integration/cmd/osrm-ranking/flags.go, integration/cmd/osrm-ranking/main.go, integration/cmd/osrm-ranking/monitor.go, integration/service/ranking/handler.go, integration/service/ranking/update_by_traffic.go
Resolves https://github.com/Telenav/osrm-backend/issues/297
- use way indexed live traffic cache instead of edge indexed in `osrm-ranking`
- If your PR is …
=> Use way indexed live traffic cache in osrm-ranking

.github/workflows/autobuild-osrm-backend.yml, CHANGELOG-FORK.md
Closes https://github.com/Telenav/osrm-backend/issues/312
- Automatically compile latest sample data and publish `telenavmap/osrm-backend-within-mapdata` docker.     
- Want to contribute? Great! First, please read this page [Contribution Guidelines](https://github.com/Telenav/osrm-backend/wiki/Contribution-Guideli …
=> Auto compile sample data

CHANGELOG-FORK.md, docker-orchestration/osrm-backend/docker-entrypoint.sh
Closes https://github.com/Telenav/osrm-backend/issues/309
- Fix wrong variable in `docker-entrypoint.sh`
- If your PR is still work in progress please …
=> Fix wrong variable in `docker-entrypoint.sh`

CHANGELOG-FORK.md, integration/cmd/osrm-ranking/flags.go, integration/cmd/osrm-ranking/main.go, integration/cmd/osrm-ranking/monitor.go, integration/pkg/api/osrm/route/response.go, integration/service/ranking/handler.go, integration/service/ranking/trafficapplyingmodel/appendonly/model.go, integration/service/ranking/trafficapplyingmodel/appendspeedonly/model.go, integration/service/ranking/trafficapplyingmodel/error.go, integration/service/ranking/trafficapplyingmodel/interface.go, integration/service/ranking/trafficapplyingmodel/invalid_speed.go, integration/service/ranking/trafficapplyingmodel/modelfactory/factory.go, integration/service/ranking/trafficapplyingmodel/preferlivetraffic/model.go, integration/service/ranking/trafficapplyingmodel/traffic_source_name.go, integration/service/ranking/update_by_traffic.go
Closes https://github.com/Telenav/osrm-backend/issues/221
- Implemented two traffic applying models:     
- appendonly: only querys traffic and append to OSRM response, no any re-calcualation 
- perferlivetraffic: prefer to use live traffic to re-calculate duration/weight on a route, use historical speed if no …
=> Recalculate by traffic

CHANGELOG-FORK.md, integration/api/oasis/request.go, integration/service/oasis/chargingstrategy/fake_charge_strategy.go, integration/service/oasis/has_enough_energy_test.go, integration/service/oasis/haversine/distance_test.go, integration/service/oasis/stationfinder/stationfinderalg/stations_iterator_alg_test.go, integration/service/oasis/stationgraph/station_graph_test.go, integration/service/ranking/trafficapplyingmodel/invalid_speed.go, integration/util/float_operation.go, integration/util/float_operation_test.go
issue: https://github.com/Telenav/osrm-backend/issues/332
Closes #332
- Add different function to compare float32 and float64, with different epsilon
- Change function name to Float64Equal         
- If your PR is …
=> feat: adjust epsilon for util/floatequals

CHANGELOG-FORK.md, integration/cmd/place-connectivity-gen/main.go, integration/service/oasis/connectivitymap/builder.go, integration/service/oasis/connectivitymap/connectivity_map.go, integration/service/oasis/connectivitymap/dumper_test.go, integration/service/oasis/handler.go, integration/service/oasis/selectionstrategy/doc.go, integration/service/oasis/selectionstrategy/has_enough_energy.go, integration/service/oasis/selectionstrategy/has_enough_energy_test.go, integration/service/oasis/selectionstrategy/reachable_by_multiple_charge.go, integration/service/oasis/selectionstrategy/reachable_by_multiple_charge_test.go, integration/service/oasis/selectionstrategy/reachable_by_single_charge.go, integration/service/oasis/selectionstrategy/reachable_by_single_charge_test.go, integration/service/oasis/selectionstrategy/resource_manager.go, integration/service/oasis/spatialindexer/poiloader/poi_format.go, integration/service/oasis/stationconnquerier/station_conn_querier.go, integration/service/oasis/stationconnquerier/station_conn_querier_test.go, integration/service/oasis/stationfinder/station_finder_factory.go, integration/service/oasis/stationfinder/stationfinderalg/stations_iterator_alg_test.go, integration/service/oasis/stationgraph/node_graph.go, integration/service/oasis/stationgraph/station_graph_test.go
issue: https://github.com/Telenav/osrm-backend/issues/242
Closes #242
integrate pre-generated connectivity data with OASIS service, got response for testing in CA. :)  Will have more test and generate performance matrix later.           
- Add filter in `node_graph`, avoid adding un-reachable stations into priority queue
+ adjust related testing cases
+ fix bug while adding end node to sorted slice
- Create new package …
=> feat: integrate pre-generated connectivity data with OASIS service

CHANGELOG-FORK.md, integration/doc/oasis/README.md, integration/doc/oasis/architecture_design.md, integration/service/oasis/spatialindexer/interface.go
issue: #359
CLOSED #359 
- Any other related issue? Mention them here.  
Related with #352  
Initial document for oasis architecture design, for more information please go to https://github.com/Telenav/osrm-backend/issues/352#issue-625240882        
- If your PR is …
=> doc: Initial document for oasis architecture design

.github/workflows/osrm-backend-ci.yml, CHANGELOG-FORK.md, include/customizer/cell_customizer.hpp, include/customizer/cell_update_record.hpp, include/partitioner/multi_level_partition.hpp, include/updater/updater.hpp, include/updater/updater_config.hpp, src/customize/customizer.cpp, src/tools/customize.cpp, src/updater/updater.cpp, unit_tests/customizer/cell_customization.cpp, unit_tests/customizer/cell_update_record.cpp, unit_tests/updater/concurrent_node_set.cpp
Closes #383 
- `.h/.cpp` changes only due to format.     
- The PR check will fail if any cpp code doesn't formatted.    
- If your PR is still work in …
=> Enable clang-format check

CHANGELOG-FORK.md, src/guidance/segregated_intersection_classification.cpp, src/util/timezones.cpp
Closes https://github.com/Telenav/osrm-backend/issues/385
Fix build error on latest macOS with Apple Clang 12. Same with https://github.com/Project-OSRM/osrm-backend/pull/5865. 
- Want to contribute? Great! First, please read this page [Contribution Guidelines](https://github.com/Telenav/osrm-backend/wiki/Contribut …
=> Fix: build error on mac OS with Apple Clang 12

CHANGELOG-FORK.md, integration/cmd/osrm-traffic-updater/osrm_traffic_updater.go, integration/service/ranking/trafficapplyingmodel/appendspeedonly/model.go, integration/service/ranking/trafficapplyingmodel/appendspeedonly/model_test.go, integration/service/ranking/trafficapplyingmodel/internal/mock/fixed_traffic.go, integration/service/ranking/trafficapplyingmodel/internal/mock/normal_traffic.go, integration/service/ranking/trafficapplyingmodel/preferlivetraffic/model_test.go, integration/util/speedunit/converter.go, integration/util/speedunit/converter_test.go
Closes https://github.com/Telenav/osrm-backend/issues/389
=> Fix unmatched speed unit between traffic flow(m/s) and OSRM traffic injection(km/h)

CHANGELOG-FORK.md, docker-orchestration/osrm-backend-within-mapdata/README.md, docker-orchestration/osrm-backend/README.md, docker-orchestration/osrm-backend/docker-entrypoint.sh, integration/cmd/osrm-rankd/main.go, integration/cmd/osrm-rankd/monitor.go
- Script to launch `osrm-rankd`
- Remove db monitor to improve `osrm-rankd` launch performance 
- Fix crash issue with flag `historical_speed=true`
- If …
=> osrm-rankd startup
